Feat/25 04
Mishank/Core-Javascript-Concepts pull request #2
Opened 2023-04-25 07:39 UTC by Mishank

2023-04-25 16:20 UTC, komarov-sergey requested changes

2023-04-25 16:20 UTC, komarov-sergey commented on src/AddingElementstotheArray.js
> +  return arr;
зачем 2й return?

2023-04-25 16:20 UTC, komarov-sergey commented on src/CheckifUserWithSuchNameExists.js
> +const users = [
Почему с заглавной название файла?

2023-04-25 16:20 UTC, komarov-sergey commented on src/ConcatenatingArrays,js
> +const mergeArrays = (arr1, arr2) => {
Почему с заглавной название файла?

2023-04-25 16:20 UTC, komarov-sergey commented on src/ConcatenatingArrays,js
> +  //   return arr1.concat(...arr2);
Зачем ты деструктишь параметр?

2023-04-25 16:20 UTC, komarov-sergey commented on src/FindtheNumberofOccurencesofMinimumValueinList.js
> +const arr = [1, 2, 3];
Почему с заглавной название файла?

2023-04-25 16:20 UTC, komarov-sergey commented on src/RemoveAllDuplicatesintheArray.js
> +const uniqueArr = (arr) => {
Пояснишь за этот код, как понял

2023-04-25 16:20 UTC, komarov-sergey commented on src/Sortingthearray.js
> +const arr = [3, 5, 1];
Почему с заглавной название файла?

2023-04-25 16:20 UTC, komarov-sergey commented on src/WritingRangeFunction.js
> +const range = (start, end) => {
Почему с заглавной название файла?

2023-04-25 16:20 UTC, komarov-sergey commented on src/WritingShuffleFunction.js
> +const shuffleItems = (items) => {
Почему с заглавной название файла?

2023-04-25 16:20 UTC, komarov-sergey commented on src/classes.js
> +class Manager extends Employee {
А где конструктор у класса?

2023-04-26 07:17 UTC, Mishank commented on src/AddingElementstotheArray.js
> +  return arr;
2 return был убран

2023-04-26 07:18 UTC, Mishank commented on src/CheckifUserWithSuchNameExists.js
> +const users = [
у меня с маленькой , возможно это ранний коммит

2023-04-26 07:19 UTC, Mishank commented on src/ConcatenatingArrays,js
> +const mergeArrays = (arr1, arr2) => {
у меня с маленькой , возможно это ранний коммит

2023-04-26 08:20 UTC, merged